[package]
authors = ["Aaron Power <theaaronepower@gmail.com>"]
name = "tokei_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
badge = "0.2"
lazy_static = "1"
mime = "0.3"
postgres = "0.15"
r2d2 = "0.8"
r2d2_postgres = "0.14"
rocket_codegen = "0.4"
tokei = "10"
dotenv = "0.14"
rocket = "0.4"
tempfile = "3.1.0"
failure = "0.1.5"
serde_json = "1.0.41"
