[package]
authors = ["Aaron Power <theaaronepower@gmail.com>"]
name = "tokei_rs"
version = "0.1.0"

[dependencies]
badge = "0.1"
lazy_static = "1"
mime = "0.3"
postgres = "0.15"
r2d2 = "0.8"
r2d2_postgres = "0.14"
tempdir = "0.3"
tokei = "6"
dotenv = "0.10"
dotenv_codegen = "0.11"
rocket = "0.4"
